# Generated by Django 5.2.17 on 2026-08-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay (UPI, QR, Netbanking)'), ('card_instant', 'Instant Credit / Debit Card'), ('card', 'Credit / Debit Card'), ('cod', 'Cash on Delivery (COD)'), ('stripe', 'Stripe Secure Checkout'), ('paypal', 'PayPal')], default='card', max_length=30),
        ),
    ]
