# Generated by Django 5.2.17 on 2026-08-25 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay (UPI, Cards, Netbanking)'), ('stripe', 'Stripe Secure Checkout'), ('card_instant', 'Instant Credit / Debit Card'), ('cod', 'Cash on Delivery (COD)')], default='razorpay', max_length=30)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('gateway_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated / Intent Created'), ('pending', 'Pending Verification'), ('success', 'Payment Successful / Captured'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded')], db_index=True, default='initiated', max_length=30)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Raw gateway response payload.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Order associated with this payment transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Refund Pending'), ('success', 'Refund Processed Successfully'), ('failed', 'Refund Failed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Refund Transaction',
                'verbose_name_plural': 'Refund Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
