# Generated by Django 5.2.17 on 2026-08-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('color_name', models.CharField(blank=True, help_text='e.g. Onyx Black, Midnight Navy, Crimson Red', max_length=64)),
                ('color_code', models.CharField(blank=True, help_text='e.g. #111827, #1e3a8a, #dc2626', max_length=30)),
                ('size', models.CharField(blank=True, help_text='e.g. XS, S, M, L, XL, XXL, 30, 32', max_length=30)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0, help_text='Available inventory units for this specific variant.')),
                ('image_url', models.URLField(blank=True, help_text='Optional color-specific photo URL.', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['color_name', 'size'],
            },
        ),
    ]
