# Generated by Django 5.2.17 on 2026-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(blank=True, default='', help_text='Associated color variant name (e.g. Red, Blue, Black). Leave blank for general.', max_length=64),
        ),
    ]
